/**
 * Runtime accessor for `app/data/generated/lfs-asset-manifest.json`.
 *
 * The manifest is generated by `scripts/ingest-lfs-assets.mjs` from the
 * (gitignored) `lfs/library/products/` tree. It maps each product handle
 * to the public-served images under `/assets/products/<handle>/...`
 * and the verbatim downloads under `/downloads/products/<handle>/...`.
 *
 * Pair with `getProductRecord()` for full content; pair with
 * `getCommerceByHandle()` for live price + stock.
 */

import manifestJson from './generated/lfs-asset-manifest.json';

export interface LfsGalleryItem {
  /** URL path under `/assets/products/...` served from `public/`. */
  publicPath: string;
  /** Original lfs path (workspace-relative, ingest-only). */
  sourcePath: string;
  sourceSha256: string;
  bytes: number;
  sha256: string;
  ext: string;
  width: number | null;
  height: number | null;
  cached: boolean;
}

export interface LfsDownloadItem {
  publicPath: string;
  sourcePath: string;
  sourceSha256: string;
  bytes: number;
  ext: string;
}

export interface LfsAssetEntry {
  name: string;
  productType: string;
  category: string | null;
  isActive: boolean;
  isHidden: boolean;
  sourceFolder: string;
  gallery: LfsGalleryItem[];
  downloads: LfsDownloadItem[];
}

interface LfsManifest {
  version: number;
  generatedAt: string;
  source: string;
  products: Record<string, LfsAssetEntry>;
}

const MANIFEST = manifestJson as unknown as LfsManifest;

export function getLfsAssetEntry(handle: string): LfsAssetEntry | null {
  return MANIFEST.products[handle] ?? null;
}

export function getLfsGalleryFirstImage(handle: string): LfsGalleryItem | null {
  const entry = MANIFEST.products[handle];
  if (!entry) return null;
  return entry.gallery[0] ?? null;
}

export function getLfsDownloads(handle: string): LfsDownloadItem[] {
  return MANIFEST.products[handle]?.downloads ?? [];
}

export function getLfsManifestMeta() {
  return {
    version: MANIFEST.version,
    generatedAt: MANIFEST.generatedAt,
    source: MANIFEST.source,
    productCount: Object.keys(MANIFEST.products).length,
  };
}
