/**
 * Runtime accessor for `app/data/generated/lfs-asset-manifest.json`.
 *
 * The manifest is generated by `scripts/ingest-lfs-assets.mjs` from the
 * committed `data/lfs-library/products/` tree (or a full local LFS mount
 * when operators pass `--source`). It maps each product handle to
 * public-served images under `/assets/products/<handle>/...` and downloads
 * under `/downloads/products/<handle>/...`.
 *
 * Pair with `getProductRecord()` for full content; pair with
 * `getCommerceByHandle()` for live price + stock.
 */

import manifestJson from './generated/lfs-asset-manifest.json';

/** Vite `import.meta.glob` keys and `LfsProductMetadata.sourcePath` prefix. */
export const COMMITTED_LFS_PRODUCTS_ROOT =
  '../../data/lfs-library/products' as const;

const MANIFEST_SOURCE_PREFIX = 'lfs/library/products/';

export interface LfsGalleryItem {
  /** URL path under `/assets/products/...` served from `public/`. */
  publicPath: string;
  /** Original lfs path (workspace-relative, ingest-only). */
  sourcePath: string;
  sourceSha256: string;
  bytes: number;
  sha256: string;
  ext: string;
  width: number | null;
  height: number | null;
  cached: boolean;
}

export interface LfsDownloadItem {
  publicPath: string;
  sourcePath: string;
  sourceSha256: string;
  bytes: number;
  ext: string;
}

export interface LfsAssetEntry {
  name: string;
  productType: string;
  category: string | null;
  isActive: boolean;
  isHidden: boolean;
  sourceFolder: string;
  gallery: LfsGalleryItem[];
  downloads: LfsDownloadItem[];
}

interface LfsManifest {
  version: number;
  generatedAt: string;
  source: string;
  products: Record<string, LfsAssetEntry>;
}

const MANIFEST = manifestJson as unknown as LfsManifest;

export function getLfsAssetEntry(handle: string): LfsAssetEntry | null {
  return MANIFEST.products[handle] ?? null;
}

export function getLfsGalleryFirstImage(handle: string): LfsGalleryItem | null {
  const entry = MANIFEST.products[handle];
  if (!entry) return null;
  return entry.gallery[0] ?? null;
}

export function getLfsDownloads(handle: string): LfsDownloadItem[] {
  return MANIFEST.products[handle]?.downloads ?? [];
}

export function getLfsManifestMeta() {
  return {
    version: MANIFEST.version,
    generatedAt: MANIFEST.generatedAt,
    source: MANIFEST.source,
    productCount: Object.keys(MANIFEST.products).length,
  };
}

/** Map a manifest `sourcePath` to the Vite glob key used under `app/data/`. */
export function manifestSourceToViteGlobKey(manifestSource: string): string {
  if (!manifestSource.startsWith(MANIFEST_SOURCE_PREFIX)) {
    return manifestSource;
  }
  return `${COMMITTED_LFS_PRODUCTS_ROOT}/${manifestSource.slice(
    MANIFEST_SOURCE_PREFIX.length,
  )}`;
}

export function manifestSourceFromViteGlobKey(
  viteGlobKey: string,
): string | null {
  const needle = '/products/';
  const idx = viteGlobKey.indexOf(needle);
  if (idx === -1) return null;
  return `${MANIFEST_SOURCE_PREFIX}${viteGlobKey.slice(idx + needle.length)}`;
}

/**
 * Resolve a bundled or public URL for a file under `data/lfs-library/products/`.
 * When no local binary is bundled (typical in CI), uses the ingest manifest.
 */
export function getManifestPublicUrlForSourcePath(
  productHandle: string | null | undefined,
  viteGlobKey: string,
): string | null {
  const manifestPath = manifestSourceFromViteGlobKey(viteGlobKey);
  if (!manifestPath) return null;

  const scanEntry = (entry: LfsAssetEntry | undefined) => {
    if (!entry) return null;
    for (const item of entry.gallery) {
      if (item.sourcePath === manifestPath) return item.publicPath;
    }
    for (const item of entry.downloads) {
      if (item.sourcePath === manifestPath) return item.publicPath;
    }
    return null;
  };

  if (productHandle) {
    const direct = scanEntry(MANIFEST.products[productHandle]);
    if (direct) return direct;
  }

  for (const entry of Object.values(MANIFEST.products)) {
    const hit = scanEntry(entry);
    if (hit) return hit;
  }

  return null;
}
